language: csharp
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
dotnet: 2.1.300
mono: latest
dist: trusty
sudo: false
install:
  - dotnet restore
script:
  - dotnet test ./test/Unosquare.Swan.AspNetCore.Test/Unosquare.Swan.AspNetCore.Test.csproj -f netcoreapp2.0
